export type Role = 'warder' | 'prisoner';
export interface Rules {mode: 'classic' | 'stage' | 'special'; size: number; bot: string; stage: number; modifiers: string[]; powers: string; analysis: boolean; personality: string; player_role: string}
export interface GameState {rules: Rules; tiles: string[]; positions: Record<Role,number|null>; tunnels: number[]; real_tunnel: number|null; key: number|null; has_key: boolean; turn: Role; ply: number; winner: Role|null; reason: string; charges: Record<Role,Record<string,number>>; pickups: Record<string,string>; roadblocks: Record<string,number>; smoke_until:number; radar_until:number; last_event:string; role:Role; rounds:number; seconds:number; tunnel_pressure:Record<string,number>; shift_cooldown:number}
export interface Estimate {prisoner:number; warder:number; unresolved:number; samples:number; target:number; horizon:number; policy:string; elapsed_ms:number; prisoner_pct:number}
export interface Analysis {estimate:Estimate; coach:{category:string; delta:number; before_samples:number}|null}
export interface Player {id:string; name:string; score:number; role:Role; online:boolean}
export interface Room {ready:string[]; activity:string[]; coaches:{ply:number;coach:Analysis["coach"]}|null; id:string; match_id:string; phase:string; rules:Rules; state:GameState|null; players:Player[]; deadline:number|null; remaining:number; rematch:string[]; analysis:Analysis|null; bot_info:{policy?:string; depth?:number; fallback?:boolean; elapsed_ms?:number; error?:string}; map_metrics:Record<string,string|number>}
export interface Lobby {online:{id:string;name:string;room:string|null}[];rooms:{id:string;mode:string;size:number;players:string[];phase:string;rules:Rules}[]}
export interface Training {status:string; episodes?:number; completed?:number; metrics:{episode:number;win_rate:number;warder_win_rate?:number;prisoner_win_rate?:number;unresolved:number;samples:number;states:number}[]; coverage?:{size:number;modifiers:string[];powers:string;personality?:string}; elapsed_seconds?:number; states?:number; error?:string}
export interface Admin {clients:Lobby['online'];rooms:{id:string;phase:string;mode:string;round:number;players:string[]}[];map_candidates:number;matches:number;training_running:boolean}
